require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/environments/*'
    - 'node_modules/**/*'

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

ExampleLength:
  Exclude:
    - 'spec/**/*'

DescribeClass:
  Exclude:
    - 'spec/system/*'
