development:
  adapter: postgresql
  encoding: unicode
  database: base_rails_project
  pool: 5
  username: robsmith
  password:
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: base_rails_project_test
  pool: 5
  username: robsmith
  password:
  timeout: 5000
